In [16]:
x = np.array([[1.,-1.,2.],[2.,0.,0.],[0.,1.,1.]],dtype=np.float64)

In [17]:
x

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1.,  1.]])

In [18]:
from sklearn import preprocessing
y = preprocessing.MinMaxScaler().fit_transform(x)

## 特征处理之文本型

In [3]:
 from sklearn.feature_extraction.text import CountVectorizer
 vectorizer = CountVectorizer(min_df=1)

In [4]:
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [5]:
corpus = ['this is the first document','this is the second document']

In [6]:
tmp = vectorizer.fit_transform(corpus)

In [8]:
print(tmp)

  (0, 0)	1
  (0, 1)	1
  (0, 4)	1
  (0, 2)	1
  (0, 5)	1
  (1, 3)	1
  (1, 0)	1
  (1, 4)	1
  (1, 2)	1
  (1, 5)	1

In [12]:
#导入数据并观察数据特点
import numpy as np
import pandas as pd
data = pd.read_csv('kaggle_bike_competition_train.csv', header = 0, error_bad_lines=False)
data.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011/1/1 0:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011/1/1 1:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011/1/1 2:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011/1/1 3:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011/1/1 4:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

In [18]:
temp = pd.DatetimeIndex(data['datetime'])
print(temp)
data['date'] = temp.date
data['time'] = temp.time
data['hour'] = pd.to_datetime(data.time,format="%H:%M:%S")
data['hour'] = pd.Index(data['hour']).hour
data.head()

DatetimeIndex(['2011-01-01 00:00:00', '2011-01-01 01:00:00',
               '2011-01-01 02:00:00', '2011-01-01 03:00:00',
               '2011-01-01 04:00:00', '2011-01-01 05:00:00',
               '2011-01-01 06:00:00', '2011-01-01 07:00:00',
               '2011-01-01 08:00:00', '2011-01-01 09:00:00',
               ...
               '2012-12-19 14:00:00', '2012-12-19 15:00:00',
               '2012-12-19 16:00:00', '2012-12-19 17:00:00',
               '2012-12-19 18:00:00', '2012-12-19 19:00:00',
               '2012-12-19 20:00:00', '2012-12-19 21:00:00',
               '2012-12-19 22:00:00', '2012-12-19 23:00:00'],
              dtype='datetime64[ns]', name='datetime', length=10886, freq=None)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date,time,hour
0,2011/1/1 0:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16,2011-01-01,00:00:00,0
1,2011/1/1 1:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40,2011-01-01,01:00:00,1
2,2011/1/1 2:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32,2011-01-01,02:00:00,2
3,2011/1/1 3:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13,2011-01-01,03:00:00,3
4,2011/1/1 4:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1,2011-01-01,04:00:00,4

In [21]:
data['dayofweek'] = pd.DatetimeIndex(data.date).dayofweek
data['dayofweek'] = (data.date - data.date[0]).astype('timedelta64[D]')

In [22]:
data

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date,time,hour,dayofweek
0,2011/1/1 0:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16,2011-01-01,00:00:00,0,0.0
1,2011/1/1 1:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40,2011-01-01,01:00:00,1,0.0
2,2011/1/1 2:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32,2011-01-01,02:00:00,2,0.0
3,2011/1/1 3:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13,2011-01-01,03:00:00,3,0.0
4,2011/1/1 4:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1,2011-01-01,04:00:00,4,0.0
5,2011/1/1 5:00,1,0,0,2,9.84,12.880,75,6.0032,0,1,1,2011-01-01,05:00:00,5,0.0
6,2011/1/1 6:00,1,0,0,1,9.02,13.635,80,0.0000,2,0,2,2011-01-01,06:00:00,6,0.0
7,2011/1/1 7:00,1,0,0,1,8.20,12.880,86,0.0000,1,2,3,2011-01-01,07:00:00,7,0.0
8,2011/1/1 8:00,1,0,0,1,9.84,14.395,75,0.0000,1,7,8,2011-01-01,08:00:00,8,0.0
9,2011/1/1 9:00,1,0,0,1,13.12,17.425,76,0.0000,8,6,14,2011-01-01,09:00:00,9,0.0
10,2011/1/1 10:00,1,0,0,1,15.58,19.695,76,16.9979,12,24,36,2011-01-01,10:00:00,10,0.0
11,2011/1/1 11:00,1,0,0,1,14.76,16.665,81,19.0012,26,30,56,2011-01-01,11:00:00,11,0.0
12,2011/1/1 12:00,1,0,0,1,17.22,21.210,77,19.0012,29,55,84,2011-01-01,12:00:00,12,0.0
13,2011/1/1 13:00,1,0,0,2,18.86,22.725,72,19.9995,47,47,94,2011-01-01,13:00:00,13,0.0
14,2011/1/1 14:00,1,0,0,2,18.86,22.725,72,19.0012,35,71,106,2011-01-01,14:00:00,14,0.0
15,2011/1/1 15:00,1,0,0,2,18.04,21.970,77,19.9995,40,70,110,2011-01-01,15:00:00,15,0.0
16,2011/1/1 16:00,1,0,0,2,17.22,21.210,82,19.9995,41,52,93,2011-01-01,16:00:00,16,0.0
17,2011/1/1 17:00,1,0,0,2,18.04,21.970,82,19.0012,15,52,67,2011-01-01,17:00:00,17,0.0
18,2011/1/1 18:00,1,0,0,3,17.22,21.210,88,16.9979,9,26,35,2011-01-01,18:00:00,18,0.0
19,2011/1/1 19:00,1,0,0,3,17.22,21.210,88,16.9979,6,31,37,2011-01-01,19:00:00,19,0.0
20,2011/1/1 20:00,1,0,0,2,16.40,20.455,87,16.9979,11,25,36,2011-01-01,20:00:00,20,0.0
21,2011/1/1 21:00,1,0,0,2,16.40,20.455,87,12.9980,3,31,34,2011-01-01,21:00:00,21,0.0
22,2011/1/1 22:00,1,0,0,2,16.40,20.455,94,15.0013,11,17,28,2011-01-01,22:00:00,22,0.0
23,2011/1/1 23:00,1,0,0,2,18.86,22.725,88,19.9995,15,24,39,2011-01-01,23:00:00,23,0.0
24,2011/1/2 0:00,1,0,0,2,18.86,22.725,88,19.9995,4,13,17,2011-01-02,00:00:00,0,1.0
25,2011/1/2 1:00,1,0,0,2,18.04,21.970,94,16.9979,1,16,17,2011-01-02,01:00:00,1,1.0
26,2011/1/2 2:00,1,0,0,2,17.22,21.210,100,19.0012,1,8,9,2011-01-02,02:00:00,2,1.0
27,2011/1/2 3:00,1,0,0,2,18.86,22.725,94,12.9980,2,4,6,2011-01-02,03:00:00,3,1.0
28,2011/1/2 4:00,1,0,0,2,18.86,22.725,94,12.9980,2,1,3,2011-01-02,04:00:00,4,1.0
29,2011/1/2 6:00,1,0,0,3,17.22,21.210,77,19.9995,0,2,2,2011-01-02,06:00:00,6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10856,2012/12/18 18:00,4,0,1,1,15.58,19.695,46,22.0028,13,512,525,2012-12-18,18:00:00,18,717.0
10857,2012/12/18 19:00,4,0,1,1,15.58,19.695,46,26.0027,19,334,353,2012-12-18,19:00:00,19,717.0
10858,2012/12/18 20:00,4,0,1,1,14.76,16.665,50,16.9979,4,264,268,2012-12-18,20:00:00,20,717.0
10859,2012/12/18 21:00,4,0,1,1,14.76,17.425,50,15.0013,9,159,168,2012-12-18,21:00:00,21,717.0
10860,2012/12/18 22:00,4,0,1,1,13.94,16.665,49,0.0000,5,127,132,2012-12-18,22:00:00,22,717.0
10861,2012/12/18 23:00,4,0,1,1,13.94,17.425,49,6.0032,1,80,81,2012-12-18,23:00:00,23,717.0
10862,2012/12/19 0:00,4,0,1,1,12.30,15.910,61,0.0000,6,35,41,2012-12-19,00:00:00,0,718.0
10863,2012/12/19 1:00,4,0,1,1,12.30,15.910,65,6.0032,1,14,15,2012-12-19,01:00:00,1,718.0
10864,2012/12/19 2:00,4,0,1,1,11.48,15.150,65,6.0032,1,2,3,2012-12-19,02:00:00,2,718.0
10865,2012/12/19 3:00,4,0,1,1,10.66,13.635,75,8.9981,0,5,5,2012-12-19,03:00:00,3,718.0
10866,2012/12/19 4:00,4,0,1,1,9.84,12.120,75,8.9981,1,6,7,2012-12-19,04:00:00,4,718.0
10867,2012/12/19 5:00,4,0,1,1,10.66,14.395,75,6.0032,2,29,31,2012-12-19,05:00:00,5,718.0
10868,2012/12/19 6:00,4,0,1,1,9.84,12.880,75,6.0032,3,109,112,2012-12-19,06:00:00,6,718.0
10869,2012/12/19 7:00,4,0,1,1,10.66,13.635,75,8.9981,3,360,363,2012-12-19,07:00:00,7,718.0
10870,2012/12/19 8:00,4,0,1,1,9.84,12.880,87,7.0015,13,665,678,2012-12-19,08:00:00,8,718.0
10871,2012/12/19 9:00,4,0,1,1,11.48,14.395,75,7.0015,8,309,317,2012-12-19,09:00:00,9,718.0
10872,2012/12/19 10:00,4,0,1,1,13.12,16.665,70,7.0015,17,147,164,2012-12-19,10:00:00,10,718.0
10873,2012/12/19 11:00,4,0,1,1,16.40,20.455,54,15.0013,31,169,200,2012-12-19,11:00:00,11,718.0
10874,2012/12/19 12:00,4,0,1,1,16.40,20.455,54,19.0012,33,203,236,2012-12-19,12:00:00,12,718.0
10875,2012/12/19 13:00,4,0,1,1,17.22,21.210,50,12.9980,30,183,213,2012-12-19,13:00:00,13,718.0
10876,2012/12/19 14:00,4,0,1,1,17.22,21.210,50,12.9980,33,185,218,2012-12-19,14:00:00,14,718.0
10877,2012/12/19 15:00,4,0,1,1,17.22,21.210,50,19.0012,28,209,237,2012-12-19,15:00:00,15,718.0
10878,2012/12/19 16:00,4,0,1,1,17.22,21.210,50,23.9994,37,297,334,2012-12-19,16:00:00,16,718.0
10879,2012/12/19 17:00,4,0,1,1,16.40,20.455,50,26.0027,26,536,562,2012-12-19,17:00:00,17,718.0
10880,2012/12/19 18:00,4,0,1,1,15.58,19.695,50,23.9994,23,546,569,2012-12-19,18:00:00,18,718.0
10881,2012/12/19 19:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336,2012-12-19,19:00:00,19,718.0
10882,2012/12/19 20:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241,2012-12-19,20:00:00,20,718.0
10883,2012/12/19 21:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168,2012-12-19,21:00:00,21,718.0
10884,2012/12/19 22:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129,2012-12-19,22:00:00,22,718.0
10885,2012/12/19 23:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88,2012-12-19,23:00:00,23,718.0

In [26]:
byday = data.groupby('dayofweek')
print(byday['casual'].sum().reset_index())

     dayofweek  casual
0          0.0     331
1          1.0     131
2          2.0     120
3          3.0     108
4          4.0      82
5          5.0      88
6          6.0     148
7          7.0      68
8          8.0      54
9          9.0      41
10        10.0      43
11        11.0      25
12        12.0      38
13        13.0      54
14        14.0     222
15        15.0     251
16        16.0     117
17        17.0       9
18        18.0      78
19        31.0      47
20        32.0      72
21        33.0      61
22        34.0      88
23        35.0     100
24        36.0     354
25        37.0     120
26        38.0      64
27        39.0      53
28        40.0      47
29        41.0     149
..         ...     ...
426      678.0     709
427      679.0    2090
428      680.0    2290
429      681.0    1097
430      682.0     327
431      683.0     373
432      684.0     320
433      685.0     484
434      686.0    1313
435      687.0     922
436      688.0     449
437      700.0     951
438      701.0     892
439      702.0     555
440      703.0     551
441      704.0     331
442      705.0     340
443      706.0     349
444      707.0    1153
445      708.0     441
446      709.0     329
447      710.0     282
448      711.0     310
449      712.0     425
450      713.0     429
451      714.0     767
452      715.0     538
453      716.0     212
454      717.0     433
455      718.0     333

[456 rows x 2 columns]

In [30]:
byday['registered'].sum().reset_index()

     dayofweek  registered
0          0.0         654
1          1.0         670
2          2.0        1229
3          3.0        1454
4          4.0        1518
5          5.0        1518
6          6.0        1362
7          7.0         891
8          8.0         768
9          9.0        1280
10        10.0        1220
11        11.0        1137
12        12.0        1368
13        13.0        1367
14        14.0        1026
15        15.0         953
16        16.0         883
17        17.0         674
18        18.0        1572
19        31.0        1313
20        32.0        1454
21        33.0        1489
22        34.0        1620
23        35.0         905
24        36.0        1269
25        37.0        1592
26        38.0        1466
27        39.0        1552
28        40.0        1491
29        41.0        1597
..         ...         ...
426      678.0        5283
427      679.0        4446
428      680.0        4562
429      681.0        5172
430      682.0        3767
431      683.0        5122
432      684.0        5125
433      685.0        5214
434      686.0        4316
435      687.0        3747
436      688.0        5050
437      700.0        4240
438      701.0        3757
439      702.0        5679
440      703.0        6055
441      704.0        5398
442      705.0        5035
443      706.0        4659
444      707.0        4429
445      708.0        2787
446      709.0        4841
447      710.0        5219
448      711.0        5009
449      712.0        5107
450      713.0        5182
451      714.0        4280
452      715.0        3248
453      716.0        4373
454      717.0        5124
455      718.0        4934

[456 rows x 2 columns]

In [31]:
data['Saturday']=0
data.Saturday[data.dayofweek==5]=1
data['Sunday']=0
data.Sunday[data.dayofweek==6]=1
print(data)

               datetime  season  holiday  workingday  weather   temp   atemp  \
0         2011/1/1 0:00       1        0           0        1   9.84  14.395
1         2011/1/1 1:00       1        0           0        1   9.02  13.635
2         2011/1/1 2:00       1        0           0        1   9.02  13.635
3         2011/1/1 3:00       1        0           0        1   9.84  14.395
4         2011/1/1 4:00       1        0           0        1   9.84  14.395
5         2011/1/1 5:00       1        0           0        2   9.84  12.880
6         2011/1/1 6:00       1        0           0        1   9.02  13.635
7         2011/1/1 7:00       1        0           0        1   8.20  12.880
8         2011/1/1 8:00       1        0           0        1   9.84  14.395
9         2011/1/1 9:00       1        0           0        1  13.12  17.425
10       2011/1/1 10:00       1        0           0        1  15.58  19.695
11       2011/1/1 11:00       1        0           0        1  14.76  16.665
12       2011/1/1 12:00       1        0           0        1  17.22  21.210
13       2011/1/1 13:00       1        0           0        2  18.86  22.725
14       2011/1/1 14:00       1        0           0        2  18.86  22.725
15       2011/1/1 15:00       1        0           0        2  18.04  21.970
16       2011/1/1 16:00       1        0           0        2  17.22  21.210
17       2011/1/1 17:00       1        0           0        2  18.04  21.970
18       2011/1/1 18:00       1        0           0        3  17.22  21.210
19       2011/1/1 19:00       1        0           0        3  17.22  21.210
20       2011/1/1 20:00       1        0           0        2  16.40  20.455
21       2011/1/1 21:00       1        0           0        2  16.40  20.455
22       2011/1/1 22:00       1        0           0        2  16.40  20.455
23       2011/1/1 23:00       1        0           0        2  18.86  22.725
24        2011/1/2 0:00       1        0           0        2  18.86  22.725
25        2011/1/2 1:00       1        0           0        2  18.04  21.970
26        2011/1/2 2:00       1        0           0        2  17.22  21.210
27        2011/1/2 3:00       1        0           0        2  18.86  22.725
28        2011/1/2 4:00       1        0           0        2  18.86  22.725
29        2011/1/2 6:00       1        0           0        3  17.22  21.210
...                 ...     ...      ...         ...      ...    ...     ...
10856  2012/12/18 18:00       4        0           1        1  15.58  19.695
10857  2012/12/18 19:00       4        0           1        1  15.58  19.695
10858  2012/12/18 20:00       4        0           1        1  14.76  16.665
10859  2012/12/18 21:00       4        0           1        1  14.76  17.425
10860  2012/12/18 22:00       4        0           1        1  13.94  16.665
10861  2012/12/18 23:00       4        0           1        1  13.94  17.425
10862   2012/12/19 0:00       4        0           1        1  12.30  15.910
10863   2012/12/19 1:00       4        0           1        1  12.30  15.910
10864   2012/12/19 2:00       4        0           1        1  11.48  15.150
10865   2012/12/19 3:00       4        0           1        1  10.66  13.635
10866   2012/12/19 4:00       4        0           1        1   9.84  12.120
10867   2012/12/19 5:00       4        0           1        1  10.66  14.395
10868   2012/12/19 6:00       4        0           1        1   9.84  12.880
10869   2012/12/19 7:00       4        0           1        1  10.66  13.635
10870   2012/12/19 8:00       4        0           1        1   9.84  12.880
10871   2012/12/19 9:00       4        0           1        1  11.48  14.395
10872  2012/12/19 10:00       4        0           1        1  13.12  16.665
10873  2012/12/19 11:00       4        0           1        1  16.40  20.455
10874  2012/12/19 12:00       4        0           1        1  16.40  20.455
10875  2012/12/19 13:00       4        0           1        1  17.22  21.210
10876  2012/12/19 14:00       4        0           1        1  17.22  21.210
10877  2012/12/19 15:00       4        0           1        1  17.22  21.210
10878  2012/12/19 16:00       4        0           1        1  17.22  21.210
10879  2012/12/19 17:00       4        0           1        1  16.40  20.455
10880  2012/12/19 18:00       4        0           1        1  15.58  19.695
10881  2012/12/19 19:00       4        0           1        1  15.58  19.695
10882  2012/12/19 20:00       4        0           1        1  14.76  17.425
10883  2012/12/19 21:00       4        0           1        1  13.94  15.910
10884  2012/12/19 22:00       4        0           1        1  13.94  17.425
10885  2012/12/19 23:00       4        0           1        1  13.12  16.665

       humidity  windspeed  casual  registered  count        date      time  \
0            81     0.0000       3          13     16  2011-01-01  00:00:00
1            80     0.0000       8          32     40  2011-01-01  01:00:00
2            80     0.0000       5          27     32  2011-01-01  02:00:00
3            75     0.0000       3          10     13  2011-01-01  03:00:00
4            75     0.0000       0           1      1  2011-01-01  04:00:00
5            75     6.0032       0           1      1  2011-01-01  05:00:00
6            80     0.0000       2           0      2  2011-01-01  06:00:00
7            86     0.0000       1           2      3  2011-01-01  07:00:00
8            75     0.0000       1           7      8  2011-01-01  08:00:00
9            76     0.0000       8           6     14  2011-01-01  09:00:00
10           76    16.9979      12          24     36  2011-01-01  10:00:00
11           81    19.0012      26          30     56  2011-01-01  11:00:00
12           77    19.0012      29          55     84  2011-01-01  12:00:00
13           72    19.9995      47          47     94  2011-01-01  13:00:00
14           72    19.0012      35          71    106  2011-01-01  14:00:00
15           77    19.9995      40          70    110  2011-01-01  15:00:00
16           82    19.9995      41          52     93  2011-01-01  16:00:00
17           82    19.0012      15          52     67  2011-01-01  17:00:00
18           88    16.9979       9          26     35  2011-01-01  18:00:00
19           88    16.9979       6          31     37  2011-01-01  19:00:00
20           87    16.9979      11          25     36  2011-01-01  20:00:00
21           87    12.9980       3          31     34  2011-01-01  21:00:00
22           94    15.0013      11          17     28  2011-01-01  22:00:00
23           88    19.9995      15          24     39  2011-01-01  23:00:00
24           88    19.9995       4          13     17  2011-01-02  00:00:00
25           94    16.9979       1          16     17  2011-01-02  01:00:00
26          100    19.0012       1           8      9  2011-01-02  02:00:00
27           94    12.9980       2           4      6  2011-01-02  03:00:00
28           94    12.9980       2           1      3  2011-01-02  04:00:00
29           77    19.9995       0           2      2  2011-01-02  06:00:00
...         ...        ...     ...         ...    ...         ...       ...
10856        46    22.0028      13         512    525  2012-12-18  18:00:00
10857        46    26.0027      19         334    353  2012-12-18  19:00:00
10858        50    16.9979       4         264    268  2012-12-18  20:00:00
10859        50    15.0013       9         159    168  2012-12-18  21:00:00
10860        49     0.0000       5         127    132  2012-12-18  22:00:00
10861        49     6.0032       1          80     81  2012-12-18  23:00:00
10862        61     0.0000       6          35     41  2012-12-19  00:00:00
10863        65     6.0032       1          14     15  2012-12-19  01:00:00
10864        65     6.0032       1           2      3  2012-12-19  02:00:00
10865        75     8.9981       0           5      5  2012-12-19  03:00:00
10866        75     8.9981       1           6      7  2012-12-19  04:00:00
10867        75     6.0032       2          29     31  2012-12-19  05:00:00
10868        75     6.0032       3         109    112  2012-12-19  06:00:00
10869        75     8.9981       3         360    363  2012-12-19  07:00:00
10870        87     7.0015      13         665    678  2012-12-19  08:00:00
10871        75     7.0015       8         309    317  2012-12-19  09:00:00
10872        70     7.0015      17         147    164  2012-12-19  10:00:00
10873        54    15.0013      31         169    200  2012-12-19  11:00:00
10874        54    19.0012      33         203    236  2012-12-19  12:00:00
10875        50    12.9980      30         183    213  2012-12-19  13:00:00
10876        50    12.9980      33         185    218  2012-12-19  14:00:00
10877        50    19.0012      28         209    237  2012-12-19  15:00:00
10878        50    23.9994      37         297    334  2012-12-19  16:00:00
10879        50    26.0027      26         536    562  2012-12-19  17:00:00
10880        50    23.9994      23         546    569  2012-12-19  18:00:00
10881        50    26.0027       7         329    336  2012-12-19  19:00:00
10882        57    15.0013      10         231    241  2012-12-19  20:00:00
10883        61    15.0013       4         164    168  2012-12-19  21:00:00
10884        61     6.0032      12         117    129  2012-12-19  22:00:00
10885        66     8.9981       4          84     88  2012-12-19  23:00:00

       hour  dayofweek  Saturday  Sunday
0         0        0.0         0       0
1         1        0.0         0       0
2         2        0.0         0       0
3         3        0.0         0       0
4         4        0.0         0       0
5         5        0.0         0       0
6         6        0.0         0       0
7         7        0.0         0       0
8         8        0.0         0       0
9         9        0.0         0       0
10       10        0.0         0       0
11       11        0.0         0       0
12       12        0.0         0       0
13       13        0.0         0       0
14       14        0.0         0       0
15       15        0.0         0       0
16       16        0.0         0       0
17       17        0.0         0       0
18       18        0.0         0       0
19       19        0.0         0       0
20       20        0.0         0       0
21       21        0.0         0       0
22       22        0.0         0       0
23       23        0.0         0       0
24        0        1.0         0       0
25        1        1.0         0       0
26        2        1.0         0       0
27        3        1.0         0       0
28        4        1.0         0       0
29        6        1.0         0       0
...     ...        ...       ...     ...
10856    18      717.0         0       0
10857    19      717.0         0       0
10858    20      717.0         0       0
10859    21      717.0         0       0
10860    22      717.0         0       0
10861    23      717.0         0       0
10862     0      718.0         0       0
10863     1      718.0         0       0
10864     2      718.0         0       0
10865     3      718.0         0       0
10866     4      718.0         0       0
10867     5      718.0         0       0
10868     6      718.0         0       0
10869     7      718.0         0       0
10870     8      718.0         0       0
10871     9      718.0         0       0
10872    10      718.0         0       0
10873    11      718.0         0       0
10874    12      718.0         0       0
10875    13      718.0         0       0
10876    14      718.0         0       0
10877    15      718.0         0       0
10878    16      718.0         0       0
10879    17      718.0         0       0
10880    18      718.0         0       0
10881    19      718.0         0       0
10882    20      718.0         0       0
10883    21      718.0         0       0
10884    22      718.0         0       0
10885    23      718.0         0       0

[10886 rows x 18 columns]

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [33]:
dataRel = data.drop(['datetime','count','date','time','dayofweek'],axis=1)
print(dataRel)

       season  holiday  workingday  weather   temp   atemp  humidity  \
0           1        0           0        1   9.84  14.395        81
1           1        0           0        1   9.02  13.635        80
2           1        0           0        1   9.02  13.635        80
3           1        0           0        1   9.84  14.395        75
4           1        0           0        1   9.84  14.395        75
5           1        0           0        2   9.84  12.880        75
6           1        0           0        1   9.02  13.635        80
7           1        0           0        1   8.20  12.880        86
8           1        0           0        1   9.84  14.395        75
9           1        0           0        1  13.12  17.425        76
10          1        0           0        1  15.58  19.695        76
11          1        0           0        1  14.76  16.665        81
12          1        0           0        1  17.22  21.210        77
13          1        0           0        2  18.86  22.725        72
14          1        0           0        2  18.86  22.725        72
15          1        0           0        2  18.04  21.970        77
16          1        0           0        2  17.22  21.210        82
17          1        0           0        2  18.04  21.970        82
18          1        0           0        3  17.22  21.210        88
19          1        0           0        3  17.22  21.210        88
20          1        0           0        2  16.40  20.455        87
21          1        0           0        2  16.40  20.455        87
22          1        0           0        2  16.40  20.455        94
23          1        0           0        2  18.86  22.725        88
24          1        0           0        2  18.86  22.725        88
25          1        0           0        2  18.04  21.970        94
26          1        0           0        2  17.22  21.210       100
27          1        0           0        2  18.86  22.725        94
28          1        0           0        2  18.86  22.725        94
29          1        0           0        3  17.22  21.210        77
...       ...      ...         ...      ...    ...     ...       ...
10856       4        0           1        1  15.58  19.695        46
10857       4        0           1        1  15.58  19.695        46
10858       4        0           1        1  14.76  16.665        50
10859       4        0           1        1  14.76  17.425        50
10860       4        0           1        1  13.94  16.665        49
10861       4        0           1        1  13.94  17.425        49
10862       4        0           1        1  12.30  15.910        61
10863       4        0           1        1  12.30  15.910        65
10864       4        0           1        1  11.48  15.150        65
10865       4        0           1        1  10.66  13.635        75
10866       4        0           1        1   9.84  12.120        75
10867       4        0           1        1  10.66  14.395        75
10868       4        0           1        1   9.84  12.880        75
10869       4        0           1        1  10.66  13.635        75
10870       4        0           1        1   9.84  12.880        87
10871       4        0           1        1  11.48  14.395        75
10872       4        0           1        1  13.12  16.665        70
10873       4        0           1        1  16.40  20.455        54
10874       4        0           1        1  16.40  20.455        54
10875       4        0           1        1  17.22  21.210        50
10876       4        0           1        1  17.22  21.210        50
10877       4        0           1        1  17.22  21.210        50
10878       4        0           1        1  17.22  21.210        50
10879       4        0           1        1  16.40  20.455        50
10880       4        0           1        1  15.58  19.695        50
10881       4        0           1        1  15.58  19.695        50
10882       4        0           1        1  14.76  17.425        57
10883       4        0           1        1  13.94  15.910        61
10884       4        0           1        1  13.94  17.425        61
10885       4        0           1        1  13.12  16.665        66

       windspeed  casual  registered  hour  Saturday  Sunday
0         0.0000       3          13     0         0       0
1         0.0000       8          32     1         0       0
2         0.0000       5          27     2         0       0
3         0.0000       3          10     3         0       0
4         0.0000       0           1     4         0       0
5         6.0032       0           1     5         0       0
6         0.0000       2           0     6         0       0
7         0.0000       1           2     7         0       0
8         0.0000       1           7     8         0       0
9         0.0000       8           6     9         0       0
10       16.9979      12          24    10         0       0
11       19.0012      26          30    11         0       0
12       19.0012      29          55    12         0       0
13       19.9995      47          47    13         0       0
14       19.0012      35          71    14         0       0
15       19.9995      40          70    15         0       0
16       19.9995      41          52    16         0       0
17       19.0012      15          52    17         0       0
18       16.9979       9          26    18         0       0
19       16.9979       6          31    19         0       0
20       16.9979      11          25    20         0       0
21       12.9980       3          31    21         0       0
22       15.0013      11          17    22         0       0
23       19.9995      15          24    23         0       0
24       19.9995       4          13     0         0       0
25       16.9979       1          16     1         0       0
26       19.0012       1           8     2         0       0
27       12.9980       2           4     3         0       0
28       12.9980       2           1     4         0       0
29       19.9995       0           2     6         0       0
...          ...     ...         ...   ...       ...     ...
10856    22.0028      13         512    18         0       0
10857    26.0027      19         334    19         0       0
10858    16.9979       4         264    20         0       0
10859    15.0013       9         159    21         0       0
10860     0.0000       5         127    22         0       0
10861     6.0032       1          80    23         0       0
10862     0.0000       6          35     0         0       0
10863     6.0032       1          14     1         0       0
10864     6.0032       1           2     2         0       0
10865     8.9981       0           5     3         0       0
10866     8.9981       1           6     4         0       0
10867     6.0032       2          29     5         0       0
10868     6.0032       3         109     6         0       0
10869     8.9981       3         360     7         0       0
10870     7.0015      13         665     8         0       0
10871     7.0015       8         309     9         0       0
10872     7.0015      17         147    10         0       0
10873    15.0013      31         169    11         0       0
10874    19.0012      33         203    12         0       0
10875    12.9980      30         183    13         0       0
10876    12.9980      33         185    14         0       0
10877    19.0012      28         209    15         0       0
10878    23.9994      37         297    16         0       0
10879    26.0027      26         536    17         0       0
10880    23.9994      23         546    18         0       0
10881    26.0027       7         329    19         0       0
10882    15.0013      10         231    20         0       0
10883    15.0013       4         164    21         0       0
10884     6.0032      12         117    22         0       0
10885     8.9981       4          84    23         0       0

[10886 rows x 13 columns]

In [39]:
from sklearn.feature_extraction import DictVectorizer
#连续值
featureConcols = ['temp','atemp','humidity','windspeed','hour']
dataFeatureCon = dataRel[featureConcols]
dataFeatureCon = dataFeatureCon.fillna('NA')
X_dictCon = dataFeatureCon.T.to_dict().values()

#存储离散值
featureCatCols = ['season','holiday','workingday','weather','Saturday','Sunday']
dataFeatureCat = dataRel[featureCatCols]
dataFeatureCat = dataFeatureCat.fillna('NA')
X_dictCat = dataFeatureCat.T.to_dict().values()

#对上述值进行向量化
vec = DictVectorizer(sparse = False)
X_vec_cat = vec.fit_transform(X_dictCat)
x_vec_con = vec.fit_transform(X_dictCon)

In [40]:
dataFeatureCon.head()

   temp   atemp  humidity  windspeed  hour
0  9.84  14.395        81        0.0     0
1  9.02  13.635        80        0.0     1
2  9.02  13.635        80        0.0     2
3  9.84  14.395        75        0.0     3
4  9.84  14.395        75        0.0     4

In [44]:
X_vec_cat
x_vec_con

array([[ 14.395 ,   0.    ,  81.    ,   9.84  ,   0.    ],
       [ 13.635 ,   1.    ,  80.    ,   9.02  ,   0.    ],
       [ 13.635 ,   2.    ,  80.    ,   9.02  ,   0.    ],
       ...,
       [ 15.91  ,  21.    ,  61.    ,  13.94  ,  15.0013],
       [ 17.425 ,  22.    ,  61.    ,  13.94  ,   6.0032],
       [ 16.665 ,  23.    ,  66.    ,  13.12  ,   8.9981]])

### 标准化连续值特征

In [45]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(x_vec_con)
x_vec_con = scaler.transform(x_vec_con)
print(x_vec_con)

[[-1.09273697 -1.66894356  0.99321305 -1.33366069 -1.56775367]
 [-1.18242083 -1.52434128  0.94124921 -1.43890721 -1.56775367]
 [-1.18242083 -1.379739    0.94124921 -1.43890721 -1.56775367]
 ...,
 [-0.91395927  1.36770431 -0.04606385 -0.80742813  0.26970368]
 [-0.73518157  1.51230659 -0.04606385 -0.80742813 -0.83244247]
 [-0.82486544  1.65690887  0.21375537 -0.91267464 -0.46560752]]

### one hot编码处理离散值特征

In [46]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc.fit(X_vec_cat)
X_vec_cat = enc.transform(X_vec_cat).toarray()
print(X_vec_cat)

[[ 1.  0.  1. ...,  0.  1.  0.]
 [ 1.  0.  1. ...,  0.  1.  0.]
 [ 1.  0.  1. ...,  0.  1.  0.]
 ...,
 [ 1.  0.  1. ...,  0.  0.  1.]
 [ 1.  0.  1. ...,  0.  0.  1.]
 [ 1.  0.  1. ...,  0.  0.  1.]]

### 拼接连续值和离散值

In [47]:
import numpy as np
X_vec = np.concatenate((x_vec_con,X_vec_cat),axis=1)
print(X_vec)

[[-1.09273697 -1.66894356  0.99321305 ...,  0.          1.          0.        ]
 [-1.18242083 -1.52434128  0.94124921 ...,  0.          1.          0.        ]
 [-1.18242083 -1.379739    0.94124921 ...,  0.          1.          0.        ]
 ...,
 [-0.91395927  1.36770431 -0.04606385 ...,  0.          0.          1.        ]
 [-0.73518157  1.51230659 -0.04606385 ...,  0.          0.          1.        ]
 [-0.82486544  1.65690887  0.21375537 ...,  0.          0.          1.        ]]

### 处理结果

In [48]:
Y_vec_reg = dataRel['registered'].values.astype(float)
Y_vec_cas = dataRel['casual'].values.astype(float)

In [50]:
Y_vec_reg

array([  13.,   32.,   27., ...,  164.,  117.,   84.])

In [51]:
Y_vec_cas

array([  3.,   8.,   5., ...,   4.,  12.,   4.])